### ISSUE TITLE
java.lang.NegativeArraySizeException when trying to align APK

### ISSUE THREAD

**Issue by JavkhlanK** [Iyxan23/zipalign-java#1]
Hi. Very cool you've been working on this!

I've implemented the library in Sketchware Pro, but it's not working for [this unsigned APK](https://github.com/Iyxan23/zipalign-java/files/8698809/NewProject.apk.unsigned.zip). Both from the cmdline and using the API directly throws this negative array size exception: 

![image](https://user-images.githubusercontent.com/40118124/168562378-3fc26b37-5ac8-470f-8dcc-85776a5e6c67.png)

**Comment by JavkhlanK** [comment]
Here compared with zipalign from AOSP:

![image](https://cdn.discordapp.com/attachments/790686719753846788/975692397038161980/Screenshot_from_2022-05-16_11-31-57.png)

**Comment by Iyxan23** [comment]
Ah, let me check it out!

**Comment by Iyxan23** [comment]
Found the issue! It seemed like I forgot to implement data descriptor, I'll do it in a bit.

Thanks for reporting!

**Comment by Iyxan23** [comment]
Hi! I have just implemented it in commit ce830808c9b59536b62fe1d33cc492655de85cc8.

Testing it with your linked apk seems to work fine!

![image](https://user-images.githubusercontent.com/31884435/168608723-413522d3-392e-41d0-9269-926392088623.png)

**Comment by JavkhlanK** [comment]
That commit seems to have fixed my issue, thanks a lot!
