### ISSUE TITLE
Wrong file is produced when align is not needed

### ISSUE THREAD

**Issue by cr4zyserb** [iyxan23/zipalign-java#11]
Error is in the code here:

```
        file.seek(0);
        if (neededAlignments.size() == 0) {
            // there is no needed alignment, stream it all!
            byte[] buffer = new byte[8192];
            while (file.read(buffer) != -1) out.write(buffer);
            return;
        }
```

should be:

```
        file.seek(0);
        if (neededAlignments.size() == 0) {
            // there is no needed alignment, stream it all!
            byte[] buffer = new byte[8192];
            int len;
            while (-1 != (len = file.read(buffer))){
                out.write(buffer, 0, len);
            }
            return;
        }
```

Original code would write extra data at the end in the most cases, except when `file_size % 8192 == 0`, which would cause **apksigner** to fail with **Malformed APK: not a ZIP archive**

**Comment by iyxan23** [comment]
Thanks for the catch! I wasn't very familiar with Java streams at the time so that was a mistake on my part 😅

Would you be kind enough to make a PR instead? So that'd count as a contribution. Thanks!

**Comment by iyxan23** [comment]
Sure, if you said so! Thanks for the fix
