### ISSUE TITLE
Publish to maven

### ISSUE THREAD

**Issue by hasrat-ali** [Iyxan23/zipalign-java#3]
Publish this library to Maven. So that, it is easy to use it for everyone in their project without jar.

**Comment by PranavPurwar** [comment]
yes

**Comment by Iyxan23** [comment]
I don't think this lib is mature enough to get into maven, I need to do more stuff first. but ok cool idea

**Comment by PranavPurwar** [comment]
ok

**Comment by hasrat-ali** [comment]
Ok, Then create a release and it will be on jitpack.

**Comment by PranavPurwar** [comment]
or someone just create a fork and publish it

**Comment by Iyxan23** [comment]
ok i don't think anything else needed to be done, i'm gonna publish this lib to jitpack

**Comment by Iyxan23** [comment]
done :>

https://jitpack.io/#Iyxan23/zipalign-java

**Comment by PranavPurwar** [comment]
pro

**Comment by hasrat-ali** [comment]
File not found. Build ok
https://jitpack.io/com/github/Iyxan23/zipalign-java/v1.0.0/zipalign-java-v1.0.0.jar

**Comment by PranavPurwar** [comment]
@hasrat-ali use 1.0.0 instead of v1.0.0 https://jitpack.io/com/github/Iyxan23/zipalign-java/1.0.0/zipalign-java-1.0.0.jar

**Comment by hasrat-ali** [comment]
Okey, thanks

**Comment by Iyxan23** [comment]
> hasrat-ali use 1.0.0 instead of v1.0.0 https://jitpack.io/com/github/Iyxan23/zipalign-java/1.0.0/zipalign-java-1.0.0.jar

any ideas to fix that? I'd like to have 1.0.0 and v1.0.0 both work

**Comment by Iyxan23** [comment]
oh wait nevermind, it is supposed to not have the `v`

**Comment by PranavPurwar** [comment]
yes, dependency version shouldn't have v
