### ISSUE TITLE
page-align uncompressed .so files

### ISSUE THREAD

**Issue by jpstotz** [iyxan23/zipalign-java#5]
Thanks for providing a Java implementation of zipalign. 

From my perspective it looks quite good, it only misses the possibilities to align .so files by 4096 instead of default 4. 

This options is becoming more and more important as recent Android Gradle plugin versions automatically set [`extractNativeLibs=false`](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) which means they are no longer extracted from the APK file upon installation, but directly used from within the APK. 
For doing so it is required to store the .so files uncompressed and align them to page boundaries (4096), independent of the value the other files are aligned to.

**Comment by Iyxan23** [comment]
Hi!

I have been thinking about adding this feature, but haven't got the time for it and it's a bit difficult to do it with the current system. It's just adding a special case for `.so` files to align it by 4096, right? I'll try to do it whenever possible, thanks for the reminder.

**Comment by hais1992** [comment]
I also need it very much. I hope the author has time to upgrade it. Thank you very much

**Comment by iyxan23** [comment]
I'm happy to share that aligning .so files will land on `1.1.0`. I had just implemented in in the branch `so-align`. Thanks guys!
